cache:
  key: ${CI_COMMIT_REF_SLUG}

.global: &global
  # Required tags setup for current worker setup.
  tags:
    - hbbft-ubuntu
  image: "rust:latest"
  variables:
    RUST_BACKTRACE: 1
    RUSTFLAGS: "-D warnings -C target-cpu=native"
    MLOCK_SECRETS: "false"

test:lint:
  <<: *global
  before_script:
    - rustup component add rustfmt-preview clippy-preview
  script:
    - cargo fmt -- --check
    - cargo clippy --tests --examples -- --deny clippy

test:cargo:
  <<: *global
  script:
    - cargo test --all-features --release
  # collect logs in case of failure
  artifacts:
    paths:
      - "net-trace*.txt"
      - "tests/*.proptest-regressions"
    expire_in: 1 week
    when: on_failure
