language: rust
rust: nightly-2018-04-19
cache: cargo
addons:
  apt:
    packages:
      - unzip
before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - sudo unzip protoc-3.5.1-linux-x86_64.zip -d /usr/local bin/protoc
  - sudo chown $(whoami) /usr/local/bin/protoc
  - protoc --version
  - rm protoc-3.5.1-linux-x86_64.zip
  - rustup component add rustfmt-preview
  - cargo install clippy -f --vers=0.0.195
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"
  script:
    - cargo fmt -- --write-mode=diff
    - cargo clippy -- -D clippy
    - cargo clippy --tests -- -D clippy
    - cargo check --tests
    - cargo test
