language: rust
rust:
    - nightly-2018-05-19
cache: cargo
addons:
  apt:
    packages:
      - unzip
before_install:
  - rustup component add rustfmt-preview
  - rustfmt --version
  - cargo install clippy -f --vers=0.0.202
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"
script:
  - cargo clippy -- -D clippy
  - cargo clippy --tests -- -D clippy
  - cargo clippy --all-features -- -D clippy
  - cargo clippy --all-features --tests -- -D clippy
  - cargo fmt -- --check
  - cargo check --tests --all-features
  - cargo test --all-features --release
