[package]
name = "hbbft"
version = "0.1.0"
authors = ["Vladimir Komendantskiy <komendantsky@gmail.com>"]

[dependencies]
env_logger = "0.5.10"
log = "0.4.1"
reed-solomon-erasure = "3.0"
merkle = { git = "https://github.com/vkomenda/merkle.rs", branch = "public-proof" }
ring = "^0.12"
protobuf = "1.4.4"
crossbeam = "0.3.2"
crossbeam-channel = "0.1"
itertools = "0.7"

[build-dependencies]
protoc-rust = "1.4.4"

[dev-dependencies]
docopt = "0.8"
rand = "0.3"
